# -*- coding: utf-8 -*-
"""Untitled44.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MMLQ5AN7JXRzt-mGFB5EOjLDmqqEYHyr
"""

import pandas as pd

import numpy as np

import matplotlib.pyplot as plt

import seaborn as sns

df=pd.read_csv("/content/sample_data/Flipkart Mobile - 2.csv new.csv")

df.head()

df.info()

df.describe()

df.shape

df.isnull().sum()

df.columns

df.boxplot(figsize=(15,15))

df.boxplot(figsize=(10,10))

df.hist(figsize=(15,15))
plt.show()

df.isnull()

df.backfill()

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report
X = df.select_dtypes(include=np.number).drop('sales', axis=1)
y = df['sales']
y = pd.cut(df['sales'], bins=2, labels=[0, 1])
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = DecisionTreeClassifier(random_state=42)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred)) # Uncomment for classification tasks

